### ISSUE TITLE
ofxTileSaver and ofGLProgrammableRenderer

### ISSUE THREAD

**Issue by julapy** [benben/ofxTileSaver#3]
theres some issues with ofxTileSaver when using the ofGLProgrammableRenderer.
ofxTileSaver calls gl functions directly, like glMatrixMode and glLoadIdentity, which is fine when using the ofGLRenderer but when using ofGLProgrammableRenderer, changing the projection and modelview matrix needs to be done through the OF API so that it works for both renderers.

issue also posted on forum,
http://forum.openframeworks.cc/t/ofxtilesaver-and-ofglprogrammablerenderer/19364

**Comment by benben** [comment]
HI @julapy, I just got the code from moka. I just edited a bit years ago to fit my needs back then. Didn't do anything lately with OF. So I cannot help you here. PRs are always welcome. I can also move this repo to a different owner if it makes sense.

**Comment by elaye** [comment]
Hi! I sent a PR that should fix the problem

**Comment by benben** [comment]
wow, awesome @elaye !

@julapy could you confirm that everything is working? if yes I would be happy to merge!

**Comment by julapy** [comment]
yeah just testing it very quickly and it seems to be working for me!
